name: Deploy CLI Package

on:
    push:
        branches: [cli/main]

jobs:
    deploy:
        name: Lint, test, build & publish CLI

        runs-on: ubuntu-latest

        steps:
            - name: ❌ Checkout repo
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: 📥 Install dependencies with Bun (with cache)
              run: bun install

            - name: 🧛 Lint CLI
              run: bun run --filter '@form-instant/cli' lint

            - name: 🔍 Type-check CLI
              run: bun run --filter '@form-instant/cli' type:check

            - name: 🛠️ Build CLI
              run: bun run --filter '@form-instant/cli' build

            - name: 🚀 Publish CLI to npm
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: packages/cli/package.json
                  access: public
